// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-feGmMpkuHF1rAY4G769YZBmGw1DzwL0',
    appId: '1:871859213428:web:3437218c43125d5c9a6d21',
    messagingSenderId: '871859213428',
    projectId: 'gishackathon-35fe9',
    authDomain: 'gishackathon-35fe9.firebaseapp.com',
    storageBucket: 'gishackathon-35fe9.appspot.com',
    measurementId: 'G-VW2CT5DL5E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBospqhW5n3il14ldngK5uvT8CI6vyPm0E',
    appId: '1:871859213428:android:809583fbb1242ffa9a6d21',
    messagingSenderId: '871859213428',
    projectId: 'gishackathon-35fe9',
    storageBucket: 'gishackathon-35fe9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbL-IoLEUG3whGtq8XeQR9zf4sHcCrAaA',
    appId: '1:871859213428:ios:9d7566ddceec72f79a6d21',
    messagingSenderId: '871859213428',
    projectId: 'gishackathon-35fe9',
    storageBucket: 'gishackathon-35fe9.appspot.com',
    iosBundleId: 'com.example.gishackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbL-IoLEUG3whGtq8XeQR9zf4sHcCrAaA',
    appId: '1:871859213428:ios:71422d868bf071a39a6d21',
    messagingSenderId: '871859213428',
    projectId: 'gishackathon-35fe9',
    storageBucket: 'gishackathon-35fe9.appspot.com',
    iosBundleId: 'com.example.gishackathon.RunnerTests',
  );
}
