// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjl37Tnw-ZTTvVXjTS8VJd-_VJt9ZTqBw',
    appId: '1:957843438680:web:3c498b910969b42d295e2d',
    messagingSenderId: '957843438680',
    projectId: 'gishackathon2',
    authDomain: 'gishackathon2.firebaseapp.com',
    storageBucket: 'gishackathon2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5GAIubJAV961gIFeZEgOcP_oEfYXyeUY',
    appId: '1:957843438680:android:c9c9b22af2ef198a295e2d',
    messagingSenderId: '957843438680',
    projectId: 'gishackathon2',
    storageBucket: 'gishackathon2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPu6Osb825ZAz7aGHfk9K81AWpP-LLMJ4',
    appId: '1:957843438680:ios:0aa73048268e8c40295e2d',
    messagingSenderId: '957843438680',
    projectId: 'gishackathon2',
    storageBucket: 'gishackathon2.appspot.com',
    iosBundleId: 'com.example.gishackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPu6Osb825ZAz7aGHfk9K81AWpP-LLMJ4',
    appId: '1:957843438680:ios:4aa3bda3a390e965295e2d',
    messagingSenderId: '957843438680',
    projectId: 'gishackathon2',
    storageBucket: 'gishackathon2.appspot.com',
    iosBundleId: 'com.example.gishackathon.RunnerTests',
  );
}
